name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: yarn install, build
        run: |
          yarn run ci
          yarn run build
      - name: run Lighthouse CI
        run: |
          yarn run lh:ci
