name: Prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.2'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: |
          yarn prettier --write .
          git diff --exit-code
