name: Prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      # Set up Node.js environment using the specified version
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1' # Align with the version specified in package.json

      # Set up pnpm (a fast, disk space efficient package manager)
      - uses: pnpm/action-setup@v2
        with:
          version: 9.14.4 # pnpm version to use, aligned with package.json

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use --no-frozen-lockfile for compatibility with current setup

      # Run Prettier and check for formatting changes
      - name: Run Prettier
        run: |
          pnpm run format  # Use the correct format script defined in package.json
          git diff --exit-code
